config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'welcome/index'

  get 'accounts/balances'

  if Mode.demo?
    resources :accounts, except: [:new, :edit, :destroy]
    resources :categories, except: [:new, :edit, :destroy]
    resources :subcategories, except: [:new, :edit, :destroy]
    resources :transactions
  else
    resources :accounts
    resources :categories
    resources :subcategories
    get 'transactions/upload'
    resources :transactions do
      collection { post :import }
    end
  end

  root 'accounts#balances'
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :transactions, :dependent => :restrict_with_exception
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def index
    @subcategories = Subcategory.all.order(name: :asc)

    # Go through all the transactions associated with this subcategory and
    # compute the net activity through that category
    # TODO: see about moving this to the Transaction model
    @nets = {}
    @subcategories.each do |subcategory|
      transactions = filter(subcategory.transactions)
      income = transactions.income.sum(:amount)
      expenses = transactions.expenses.sum(:amount)
      @nets[subcategory.id] = income - expenses
    end
  end

  def show
    # TODO: see about de-duplication of this from the index method
    @subcategory = Subcategory.find(params[:id])

    @transactions = filter(@subcategory.transactions)
    @count = @transactions.count
    @income = @transactions.income.sum(:amount)
    @expenses = @transactions.expenses.sum(:amount)
    @net = @income - @expenses
  end

  def new
    @subcategory = Subcategory.new
  end

  def edit
    @subcategory = Subcategory.find(params[:id])
  end

  def create
    @subcategory = Subcategory.new(subcategory_params)

    if @subcategory.save
      redirect_to @subcategory
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @subcategory = Subcategory.find(params[:id])

    if @subcategory.update(subcategory_params)
      redirect_to @subcategory
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    # Remove an subcategory record from the database. Restrict destruction in the
    # case where it has transactions. Don't want to leave any
    # transactions pointing to non-existent subcategories.
    @subcategory = Subcategory.find(params[:id])
    begin
      @subcategory.destroy
      flash[:success] = "Successfully deleted subcategory: #{@subcategory.name}"
      redirect_to subcategories_path, status: :see_other
    rescue ActiveRecord::DeleteRestrictionError
      flash[:error] = "Cannot delete this subcategory because it has associated transactions"
      redirect_to subcategory_path
    end
  end

  private
    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_with model: @subcategory, local: true do |form| %>

  <% if @subcategory.errors.any? %>
    <div class="error-explanation">
      <%= pluralize(@subcategory.errors.count, "error") %> prohibited
      this subcategory from being saved:
      <ul>
        <% @subcategory.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label 'Category' %>
    <%= form.collection_select(:category_id, Category.all, :id, :name, :prompt => 'Select') %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/subcategories/_subcategory.html.erb
<table>
  <tr>
    <th>Name</th>
    <td><%= @subcategory.name %></td>
  </tr>
  <tr>
    <th>Subcategory of</th>
    <td><%= link_to @subcategory.category.name, category_path(@subcategory.category) %></td>
  </tr>
</table>

app/views/subcategories/edit.html.erb
<h2>Edit subcategory</h2>

<%= render 'form' %>

<%= link_to 'Cancel', subcategory_path(@subcategory.id) %>

app/views/subcategories/index.html.erb
<h2>Subcategories</h2>

<%= render 'flash', key: :success %>

<p>
  <% if Mode.demo? %>
    <%= link_to 'Add new subcategory', subcategories_path,
      data: { confirm: 'Adding is not available in demo mode.' } %>
  <% else %>
    <%= link_to 'Add new subcategory', new_subcategory_path %>
  <% end %>
</p>

<div class="filter-area">
  <%= render 'transactions/dates' %>
</div>

<table>
  <tr>
    <th>Subcategory</th>
    <th>Net activity</th>
  </tr>

  <% @subcategories.each do |subcategory| %>
    <tr>
      <td><%= link_to subcategory.name, subcategory_path(subcategory) %></td>

      <td class="amount
      <%= 'decrease' if (@nets[subcategory.id] < 0) %>">
        <%= number_to_currency(@nets[subcategory.id], unit: CURRENCY_SIGN) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/subcategories/new.html.erb
<h2>Add a new Subcategory</h2>

<%= render 'form' %>

<%= link_to 'Cancel', subcategories_path %>

app/views/subcategories/show.html.erb
<h2>Subcategory info</h2>

<%= render 'flash', key: :error %>

<%= render 'subcategory' %>

<p>
  <%= link_to 'Previous', subcategory_path(@subcategory.previous) %> |
  <%= link_to 'Next', subcategory_path(@subcategory.next) %> |
  <% if Mode.demo? %>
    <%= link_to 'Edit', subcategory_path(@subcategory),
      data: {confirm: 'Editing is not available in demo mode'} %> |
    <%= link_to 'Delete', subcategory_path(@subcategory),
      data: { confirm: 'Deleting is not available in demo mode' } %>
  <% else %>
    <%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
    <%= link_to 'Delete', subcategory_path(@subcategory), data: {
      turbo_method: :delete, turbo_confirm: 'Are you sure?'
    } %>
  <% end %>
</p>

<h3>Transactions involving this subcategory</h3>

<%= render 'transactions/filters' %>

<%= render 'transactions/summary', content: [['Count', @count],
                                             ['Income', @income],
                                             ['Expenses', @expenses],
                                             ['Net', @net]] %>

<%= render 'transactions/table' %>