config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'welcome/index'

  get 'accounts/balances'

  if Mode.demo?
    resources :accounts, except: [:new, :edit, :destroy]
    resources :categories, except: [:new, :edit, :destroy]
    resources :subcategories, except: [:new, :edit, :destroy]
    resources :transactions
  else
    resources :accounts
    resources :categories
    resources :subcategories
    get 'transactions/upload'
    resources :transactions do
      collection { post :import }
    end
  end

  root 'accounts#balances'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions, :dependent => :restrict_with_exception
  has_many :subcategories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    # Prepare collection of categories ordered by name
    @categories = Category.all.order(name: :asc)

    # Iterate through the categories and compute net activity for each
    @nets = {}
    @categories.each do |category|
      # Get the transactions of the category subject to the current filter
      transactions = filter(category.transactions)
      # Net activity is sum(income transactions) - sum(expense transactions)
      income = transactions.income.sum(:amount)
      expenses = transactions.expenses.sum(:amount)
      @nets[category.id] = income - expenses
    end
  end

  def show
    # Show the given category and pertinent information based on id
    @category = Category.find(params[:id])

    # Perform computations on the transactions of the category and
    # TODO: investigate moving this into the Transaction model instead which
    # may be a good way to reduce duplication between this and the index method
    @transactions = filter(@category.transactions)
    @count = @transactions.count
    @income = @transactions.income.sum(:amount)
    @expenses = @transactions.expenses.sum(:amount)
    @net = @income - @expenses
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    # Remove an category record from the database. Restrict destruction in the
    # case where it has transactions. Don't want to leave any
    # transactions pointing to non-existent categories.
    @category = Category.find(params[:id])
    begin
      @category.destroy
      flash[:success] = "Successfully deleted category: #{@category.name}"
      redirect_to categories_path, status: :see_other
    rescue ActiveRecord::DeleteRestrictionError
      flash[:error] = "Cannot delete this category because it has associated transactions"
      redirect_to category_path
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<table>
  <tr>
    <th>Name</th>
    <td><%= @category.name %></td>
  </tr>
</table>

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true do |form| %>

  <% if @category.errors.any? %>
    <div class="error-explanation">
      <%= pluralize(@category.errors.count, "error") %> prohibited
      this category from being saved:
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit category</h2>

<%= render 'form' %>

<%= link_to 'Cancel', category_path(@category.id) %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<%= render 'flash', key: :success %>

<p>
  <% if Mode.demo? %>
    <%= link_to 'Add new category', categories_path,
      data: { confirm: 'Adding is not available in demo mode.' } %>
  <% else %>
    <%= link_to 'Add new category', new_category_path %>
  <% end %>
</p>

<div class="filter-area">
  <%= render 'transactions/dates' %>
</div>

<table>
  <tr>
    <th>Category</th>
    <th>Net activity</br>(for date range)</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category_path(category) %></td>

      <td class="amount
      <%= 'decrease' if (@nets[category.id] < 0) %>">
        <%= number_to_currency(@nets[category.id], unit: CURRENCY_SIGN) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h2>Add a new Category</h2>

<%= render 'form' %>

<%= link_to 'Cancel', categories_path %>

app/views/categories/show.html.erb
<h2>Category info</h2>

<%= render 'flash', key: :error %>

<%= render 'category' %>

<p>
  <%= link_to 'Previous', category_path(@category.previous) %> |
  <%= link_to 'Next', category_path(@category.next) %> |
  <% if Mode.demo? %>
    <%= link_to 'Edit', category_path(@category),
      data: {confirm: "Editing is not available in demo mode"} %> |
    <%= link_to 'Delete', category_path(@category),
      data: { confirm: 'Deleting is not available in demo mode' } %>
  <% else %>
    <%= link_to 'Edit', edit_category_path(@category) %> |
    <%= link_to 'Delete', category_path(@category), data: {
      turbo_method: :delete, turbo_confirm: 'Are you sure?'
    } %>
  <% end %>
</p>

<% if @category.subcategories.count > 0 %>
  <h3>Subcategories in this category</h3>
<% end %>

<ul>
<% @category.subcategories.order("name").each do |subcategory| %>
  <li><%= link_to subcategory.name, subcategory_path(subcategory) %></li>
<% end %>
</ul>

<h3>Transactions involving this catetory</h3>

<%= render 'transactions/filters' %>

<%= render 'transactions/summary', content: [['Count', @count],
                                             ['Income', @income],
                                             ['Expenses', @expenses],
                                             ['Net', @net]] %>

<%= render 'transactions/table' %>