config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'welcome/index'

  get 'accounts/balances'

  if Mode.demo?
    resources :accounts, except: [:new, :edit, :destroy]
    resources :categories, except: [:new, :edit, :destroy]
    resources :subcategories, except: [:new, :edit, :destroy]
    resources :transactions
  else
    resources :accounts
    resources :categories
    resources :subcategories
    get 'transactions/upload'
    resources :transactions do
      collection { post :import }
    end
  end

  root 'accounts#balances'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    # Get all transactions subject to filtering
    # Filtering includes: date range, search, and
    # QUESTION: at what point might it become poor performing to rely merely on
    # the SQL LIKE operator for search
    # https://en.wikipedia.org/wiki/Inverted_index
    # https://github.com/Casecommons/pg_search
    @transactions = filter(Transaction)

    # Get the count, and transactions by income vs expenses and compute net
    # activity across the collection of transactions
    @count = @transactions.count
    @income = @transactions.income.sum(:amount)
    @expenses = @transactions.expenses.sum(:amount)
    @net = @income - @expenses

    # Support downloading transaction data as csv
    respond_to do |format|
      format.html
      format.csv { send_data @transactions.to_csv }
    end

  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
  end

  def import
    # Action to pass the csv file via query parameter and call the import
    # method of the Transaction model
    Transaction.import(params[:file])
    redirect_to transactions_path, notice: "Transaction CSV data imported"
  end

  def upload
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new(transaction_params)

    if @transaction.save
      redirect_to @transaction
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @transaction = Transaction.find(params[:id])

    if @transaction.update(transaction_params)
      redirect_to @transaction
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    flash[:success] = "Successfully deleted transaction dated: #{@transaction.date}"

    redirect_to transactions_path, status: :see_other
  end

  private
    def transaction_params
      # Constrain valid parameters pertinent to a transaction
      params.require(:transaction).permit(:date,
                                          :amount,
                                          :description,
                                          :sender_id,
                                          :receiver_id,
                                          :category_id,
                                          :subcategory_id)
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_dates.html.erb
<%= form_tag nil, {:method => 'get', :class => 'filter-form'} do %>
  <% request.query_parameters.except(:start_date, :end_date).each do |key, value| %>
    <%= hidden_field_tag key, value %>
  <% end %>

  <%= label_tag :start_date %>
  <%= date_field_tag :start_date, params[:start_date] %>

  <%= label_tag :end_date %>
  <%= date_field_tag :end_date, params[:end_date] %>

  <%= submit_tag "Go", :name => nil %>
<% end %>

app/views/transactions/_filters.html.erb
<div class="filter-area">
  <%= render 'transactions/search' %>
  <%= render 'transactions/dates' %>
</div>

app/views/transactions/_form.html.erb
<%= form_with model: @transaction, local: true do |form| %>

  <% if @transaction.errors.any? %>
    <div class="error-explanation">
      <%= pluralize(@transaction.errors.count, "error") %> prohibited
      this transaction from being saved:
      <ul>
        <% @transaction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
  </p>
  <p>
    <%= form.label :amount %><br>
    <%= form.number_field( :amount, min: 0.01, step: 0.01) %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.label 'From' %>
    <%= form.collection_select(:sender_id, Account.order(name: :asc).all, :id, :name, :prompt => 'Select') %>
  </p>
  <p>
    <%= form.label 'To' %>
    <%= form.collection_select(:receiver_id, Account.order(name: :asc).all, :id, :name, :prompt => 'Select') %>
  </p>
  <p>
    <%= form.label 'Category' %>
    <%= form.collection_select(:category_id, Category.order(name: :asc).all, :id, :name, :prompt => 'Select') %>
  </p>
  <p>
    <%= form.label 'Subcategory' %>
    <%= form.collection_select(:subcategory_id, Subcategory.order(name: :asc).all, :id, :name, :prompt => 'Select') %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/transactions/_info.html.erb
<table>
  <tr>
    <th>Date:</th>
    <td><%= @transaction.date %></td>
  </tr>
  <tr>
    <th>Amount:</th>
    <td><%= number_to_currency(@transaction.amount, unit: CURRENCY_SIGN) %></td>
  </tr>
  <tr>
    <th>Description:</th>
    <td><%= @transaction.description %></td>
  </tr>
  <tr>
    <th>From:</th>
    <td><%= link_to @transaction.sender.name, @transaction.sender %></td>
  </tr>
  <tr>
    <th>To:</th>
    <td><%= link_to @transaction.receiver.name, @transaction.receiver %></td>
  </tr>
</table>

app/views/transactions/_search.html.erb
<%= form_tag nil, {:method => 'get', :class => 'filter-form'} do %>
  <% request.query_parameters.except(:search).each do |key, value| %>
    <%= hidden_field_tag key, value %>
  <% end %>

  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/transactions/_summary.html.erb
<div class="summary-area">
  <table>
    <tr>
      <th><%= content[0][0] %></th>
      <td class="amount"><%= content[0][1] %></td>
    </tr>
    <tr>
      <th><%= content[1][0] %></th>
      <td class="amount" ><%= number_to_currency(content[1][1], unit: CURRENCY_SIGN) %></td>
    </tr>
    <tr>
      <th><%= content[2][0] %></th>
      <td class="amount decrease" ><%= number_to_currency(content[2][1], unit: CURRENCY_SIGN) %></td>
    </tr>
    <tr>
      <th><%= content[3][0] %></th>

      <td class="amount
      <%= 'decrease' if (content[3][1] < 0) %>">
        <%= number_to_currency(content[3][1], unit: CURRENCY_SIGN) %>
      </td>

    </tr>
  </table>
</div>

app/views/transactions/_table.html.erb
<table class='transactions-table'>
  <tr>
    <th><%= sortable "date" %></th>
    <th><%= sortable "amount" %></th>
    <th><%= sortable "description" %></th>
    <th><%= sortable "sender", "From" %></th>
    <th><%= sortable "receiver", "To" %></th>

    <% unless controller_name == 'categories' %>
      <th><%= sortable "category" %></th>
    <% end %>

    <% unless controller_name == 'subcategories' %>
      <th><%= sortable "subcategory" %></th>
    <% end %>

    <th></th>
  </tr>

  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.date %></td>
      <td class="amount
      <%= 'decrease' if (!transaction.receiver.owned) %>
      <%= 'neutral' if (transaction.sender.owned) && (transaction.receiver.owned) %>">
        <%= number_to_currency(transaction.amount, unit: CURRENCY_SIGN) %>
      </td>
      <td><%= transaction.description %></td>

      <% if defined?(account) %>
        <td><%= transaction.sender != account ? link_to(transaction.sender.name, account_path(transaction.sender)) : "–" %></td>
        <td><%= transaction.receiver != account ? link_to(transaction.receiver.name, account_path(transaction.receiver)) : "–" %></td>
      <% else %>
        <td><%= link_to transaction.sender.name, account_path(transaction.sender) %></td>
        <td><%= link_to transaction.receiver.name, account_path(transaction.receiver) %></td>
      <% end %>

      <% unless controller_name == 'categories' %>
        <td><%= link_to transaction.category.name, category_path(transaction.category) %></td>
      <% end %>

      <% unless controller_name == 'subcategories' %>
        <td><%= link_to transaction.subcategory.name, subcategory_path(transaction.subcategory) if transaction.subcategory%></td>
      <% end %>

      <td><%= link_to 'Info', transaction_path(transaction) %></td>
    </tr>
  <% end %>
</table>

app/views/transactions/_transaction.html.erb
<table class="transaction-details">
  <tr>
    <th>Date</th>
    <td><%= @transaction.date %></td>
  </tr>
  <tr>
    <th>Amount</th>
    <td class="
    <%= 'decrease' if (!@transaction.receiver.owned) %>
    <%= 'neutral' if (@transaction.sender.owned) && (@transaction.receiver.owned) %>">
      <%= number_to_currency(@transaction.amount, unit: CURRENCY_SIGN) %>
    </td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @transaction.description %></td>
  </tr>
  <tr>
    <th>From</th>
    <td><%= link_to @transaction.sender.name, @transaction.sender %></td>
  </tr>
  <tr>
    <th>To</th>
    <td><%= link_to @transaction.receiver.name, @transaction.receiver %></td>
  </tr>
  <tr>
    <th>Category</th>
    <td><%= link_to @transaction.category.name, @transaction.category %></td>
  </tr>
  <tr>
    <th>Subcategory</th>
    <td>
      <%= link_to @transaction.subcategory.name, subcategory_path(@transaction.subcategory) if @transaction.subcategory %>
    </td>
  </tr>
</table>

<p>
  <% if Mode.demo? %>
    <%= link_to 'Add new transaction', nil,
      data: { confirm: 'Adding is not available in demo mode.' } %>
  <% else %>
    <%= link_to 'Add new transaction', new_transaction_path %>
  <% end %>
</p>

app/views/transactions/edit.html.erb
<h2>Edit transaction</h2>

<%= render 'form' %>

<%= link_to 'Cancel', transaction_path(@transaction.id) %>

app/views/transactions/index.html.erb
<h2>Transactions</h2>

<%= render 'flash', key: :success %>

<p>
  <% if Mode.demo? %>
    <%= link_to 'Add new transaction', transactions_path,
      data: { confirm: 'Adding is not available in demo mode.' } %> |
    <%= link_to 'Import', transactions_path,
      data: { confirm: 'Importing is not available in demo mode.' }%> |
  <% else %>
    <%= link_to 'Add new transaction', new_transaction_path %> |
    <%= link_to 'Import', '/transactions/upload' %> |
  <% end %>
  <%= link_to 'Download all', '/transactions.csv' %>
</p>

<%= render 'filters' %>

<%= render 'summary', content: [['Count', @count],
                                ['Income', @income],
                                ['Expenses', @expenses],
                                ['Net', @net]] %>

<%= render 'table' %>

app/views/transactions/new.html.erb
<h2>Add a new transaction</h2>

<%= render 'form' %>

<%= link_to 'Cancel', transactions_path %>

app/views/transactions/show.html.erb
<h2>Transaction info</h2>

<%= render 'transaction' %>

<p>
  <%= link_to 'Previous', transaction_path(@transaction.previous) %> |
  <%= link_to 'Next', transaction_path(@transaction.next) %> |

  <% if Mode.demo? %>
    <%= link_to 'Edit', transaction_path(@transaction),
      data: { confirm: 'Editing is not available in demo mode' } %> |
    <%= link_to 'Delete', transaction_path(@transaction),
      data: { confirm: 'Deleting is not available in demo mode' } %>
  <% else %>
    <%= link_to 'Edit', edit_transaction_path(@transaction) %> |
    <%= link_to 'Delete', transaction_path(@transaction), data: {
      turbo_method: :delete, turbo_confirm: 'Are you sure?'
    } %>
  <% end %>


</p>

app/views/transactions/upload.html.erb
<h2>Import transaction data from CSV</h2>

<%= form_tag import_transactions_path, {:multipart => true, :class => 'filter-form'} do %>
  <%= flash[:notice] %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<p>
  <%= link_to 'Back', transactions_path %>
</p>