config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'welcome/index'

  get 'accounts/balances'

  if Mode.demo?
    resources :accounts, except: [:new, :edit, :destroy]
    resources :categories, except: [:new, :edit, :destroy]
    resources :subcategories, except: [:new, :edit, :destroy]
    resources :transactions
  else
    resources :accounts
    resources :categories
    resources :subcategories
    get 'transactions/upload'
    resources :transactions do
      collection { post :import }
    end
  end

  root 'accounts#balances'
end

app/models/account.rb
class Account < ApplicationRecord
  # Accounts have transactions associated with them either as an input or an
  # output.
  # A transaction is an input to a given account if the transaction's
  # receiver_id is the id of this account.
  # A transaction is an output from a given account if the transaction's
  # sender_id is the id of the given account.
  # Don't permit deletion of an account if there are dependent transactions
  # Can't have any transactions referencing a non-existent account
  has_many :inputs, :class_name => 'Transaction', :foreign_key => 'receiver_id', :dependent => :restrict_with_exception
  has_many :outputs, :class_name => 'Transaction', :foreign_key => 'sender_id', :dependent => :restrict_with_exception

  # Ensure the account meets requirements for its fields
  # Validate a boolean
  # https://guides.rubyonrails.org/active_record_validations.html#presence
  validates :name, presence: true, length: {minimum: 3}
  validates :owned, inclusion: { in: [true, false] }
  validates :retirement, inclusion: { in: [true, false] }
  validates :initial, numericality: true

  def self.to_csv
    CSV.generate do |csv|
      # Manually populate the csv header row.
      # Alternatively, to do all the fields of the record:
      # https://apidock.com/rails/ActiveRecord/ModelSchema/ClassMethods/column_names
      # csv << column_names
      csv << ["name", "owned", "retirement", "initial"]
      all.each do |account|
        # Populate the row with the corresponding record fields
        csv << [account.name,
                account.owned,
                account.retirement,
                account.initial]
        # Alternatively, unpack all column names
        # csv << transaction.attributes.values_at(*column_names)
      end
    end
  end

  def balance
    # Returns the computed sum of the initial value plus all the inputs
    # minus all the outputs
    self.initial + self.inputs.sum(:amount) - self.outputs.sum(:amount)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    # Get accounts by relevant designations, ordered by name
    @accounts = Account.all.order(name: :asc)
    @owned_accounts = Account.where(owned: true).order(name: :asc)
    @external_accounts = Account.where(owned: false).order(name: :asc)
    @non_retirement_accounts = @owned_accounts.where(retirement: false).order(name: :asc)
    @retirement_accounts = @owned_accounts.where(retirement: true).order(name: :asc)

    # Go through each account and compute net activity and populate a hash to
    # pass to the view
    # QUESTION: Is there a tidier way to do this at the model level? E.g.
    # have an instance method `net_activity` which would then seemingly need
    # access to the filter. The below article seems relevant to return to
    # https://www.justinweiss.com/articles/search-and-filter-rails-models-without-bloating-your-controller/
    @nets = {}
    @accounts.each do |account|
      # The net activity (across the filtered transactions) is the sum of
      # the inputs minus the sum of the outputs
      input = filter(account.inputs).sum(:amount)
      output = filter(account.outputs).sum(:amount)
      sum = input - output
      @nets[account.id] = account.owned ? sum : -sum
    end

    # Provide for downloading all account data as a csv file
    # see: https://www.codementor.io/@victor_hazbun/export-records-to-csv-files-ruby-on-rails-vda8323q0
    respond_to do |format|
      format.html
      format.csv { send_data @accounts.to_csv }
    end

  end

  def balances
    # Special action to view the current balance of an account, computed over
    # all transactions, starting from the initial value and summing all the
    # inputs and outputs.
    # The balance of an account only makes sense where the account is owned

    # Get all owned accounts and split them based on the retirement designation
    @owned_accounts = Account.where(owned: true).order(name: :asc)
    @non_retirement_accounts = @owned_accounts.where(retirement: false).order(name: :asc)
    @retirement_accounts = @owned_accounts.where(retirement: true).order(name: :asc)

    # Iterate through all the owned accounts and sum their balances to compute
    # net worth to pass to the view
    @net_worth = 0
    @owned_accounts.each do |account|
      initial = account.initial
      @net_worth += account.balance
    end
  end

  def show
    # Show a single account and relevant values and associated transactions
    @account = Account.find(params[:id])

    # Information based on filtered transactions associated with the account
    @count = filter(@account.inputs.or(@account.outputs)).count
    @input = filter(@account.inputs).sum(:amount)
    @output = filter(@account.outputs).sum(:amount)
    sum = @input - @output

    # Invert the net activity of the account if it is not owned
    # this is because the perspective to you is flipped for external accounts
    @net = @account.owned ? sum : -sum

    # Get all relevant transactions to this account whether they be inputs or
    # outputs
    combined = combined = @account.inputs.or(@account.outputs)
    @transactions = filter(combined)
  end

  def new
    # Create a new account via html form
    @account = Account.new
  end

  def edit
    # Edit the given account by id via html form
    @account = Account.find(params[:id])
  end

  def create
    # Attempt to save a new account to the database. if there are problems,
    # render the form again (and the view is to present the problems)
    @account = Account.new(account_params)

    if @account.save
      redirect_to @account
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    # Modify the account by id via html form and attempt to save it to the
    # database. If there are problems render the form again and show them.
    @account = Account.find(params[:id])

    if @account.update(account_params)
      redirect_to @account
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    # Remove an account record from the database. Restrict destruction in the
    # case where an account has transactions. Don't want to leave any
    # transactions pointing to non-existent accounts.
    @account = Account.find(params[:id])

    # Try and destroy the account and prepare a success flash message
    begin
      @account.destroy
      flash[:success] = "Successfully deleted account: #{@account.name}"
      redirect_to accounts_path, status: :see_other
    # Catch for the case where destruction isn't allowed and prepare a flash
    rescue ActiveRecord::DeleteRestrictionError
      flash[:error] = "Cannot delete this account because it has associated
      transactions"
      redirect_to account_path
    end
  end

  private
    def account_params
      # Stipulate the parameters of an account explicitly
      params.require(:account).permit(:name, :owned, :retirement, :initial, :reconciled_on)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<table>
  <tr>
    <th>Name</th>
    <td><%= @account.name %></td>
  </tr>
  <tr>
    <th>Owned by me?</th>
    <td><%= @account.owned %></td>
  </tr>
  <tr>
    <th>Retirement account?</th>
    <td><%= @account.retirement %></td>
  </tr>
  <tr>
    <th>Initial value</th>
    <% if @account.owned %>
      <td class="amount" ><%= number_to_currency(@account.initial, unit: CURRENCY_SIGN) %></td>
    <% else %>
      <td>N/A</td>
    <% end %>
  </tr>
  <tr>
    <th>Reconciled on</th>
    <% if @account.reconciled_on %>
      <td><%= @account.reconciled_on %></td>
    <% else %>
      <td>nil</td>
    <% end %>
  </tr>
</table>

<table>
  <tr>
    <th>Balance</th>
    <td class="amount <%= 'decrease' if (@account.balance < 0) %>">
      <%= number_to_currency(@account.balance, unit: CURRENCY_SIGN) %>
    </td>
  </tr>
  <tr>
    <th>Last reconciled</th>
    <td><%= render 'reconciled', account: @account %></td>
  </tr>
</table>

app/views/accounts/_activity_table.html.erb
<% unless accounts.empty? %>
  <table>
      <tr>
        <th>
          <%= defined?(header) ? header : 'Account' %>
        </th>
        <th>Net activity</br>(for date range)</th>
      </tr>

      <% accounts.each do |account| %>
        <tr>
          <td><%= link_to account.name, account_path(account) %></td>

          <td class="amount
          <%= 'decrease' if (nets[account.id] < 0) %>">
          <%= number_to_currency(nets[account.id], unit: CURRENCY_SIGN) %>
          </td>
        </tr>
      <% end %>
  </table>
<% end %>

app/views/accounts/_balances_table.html.erb
<table>
  <tr>
    <th>Account</th>
    <th>Balance</th>
    <th>Last reconciled</th>
  </tr>

  <% total = 0 %>
  <% accounts.each do |account| %>
  <% total += account.balance %>
    <tr>
      <td><%= link_to account.name, account_path(account) %></td>
      <td class="amount <%= 'decrease' if (account.balance < 0) %>">
        <%= number_to_currency(account.balance, unit: CURRENCY_SIGN) %>
      </td>
      <td><%= render 'reconciled', account: account%></td>
    </tr>
  <% end %>

  <tr>
    <th>Total</th>
    <th class="amount <%= 'decrease' if (total < 0) %>">
      <%= number_to_currency(total, unit: CURRENCY_SIGN) %>
    </th>
  </tr>
</table>

app/views/accounts/_form.html.erb
<%= form_with model: @account, local: true do |form| %>

  <% if @account.errors.any? %>
    <div class="error-explanation">
      <%= pluralize(@account.errors.count, "error") %> prohibited
      this account from being saved:
      <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :owned %><br>
    <%= form.check_box :owned %>
  </p>
  <p>
    <%= form.label :retirement %><br>
    <%= form.check_box :retirement %>
  </p>
  <p>
    <%= form.label :initial %><br>
    <%= form.number_field(:initial, step: 0.01) %>
  </p>
  <p>
    <%= form.label :reconciled_on %><br>
    <%= form.date_field :reconciled_on %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/accounts/_reconciled.html.erb
<% if account.reconciled_on %>

  <% if account.reconciled_on == Date.today %>
    Today
  <% elsif account.reconciled_on > Date.today %>
    <%= time_ago_in_words(account.reconciled_on) %> from now
  <% else %>
    <%= time_ago_in_words(account.reconciled_on) %> ago
  <% end %>

<% else %>

  never

<% end %>

app/views/accounts/_table.html.erb
<table>
  <tr>
    <th>Account</th>
    <th>Net activity</th>
  </tr>

  <% accounts.each do |account| %>
    <tr>
      <td><%= link_to account.name, account_path(account) %></td>

      <td class="amount
      <%= 'decrease' if (nets[account.id] < 0) %>">
        <%= number_to_currency(nets[account.id], unit: CURRENCY_SIGN) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/accounts/balances.html.erb
<h2>Balances</h2>

<h3>Non-retirement</h3>

<%= render 'balances_table', accounts: @non_retirement_accounts, balances: @balances %>

<h3>Retirement:</h3>

<%= render 'balances_table', accounts: @retirement_accounts, balances: @balances %>

<h3>Net worth:</h3>

<table>
  <tr>
    <th class="amount
      <%= 'decrease' if (@net_worth < 0) %>">
        <%= number_to_currency(@net_worth, unit: CURRENCY_SIGN) %>
    </th>
  <tr>
</table>

app/views/accounts/edit.html.erb
<h2>Edit account</h2>

<%= render 'form' %>

<%= link_to 'Cancel', account_path(@account.id) %>

app/views/accounts/index.html.erb
<h2>Accounts</h2>

<%= render 'flash', key: :success %>

<p>
  <% if Mode.demo? %>
    <%= link_to 'Add new account', accounts_path,
      data: { confirm: 'Adding is not available in demo mode.' } %>
  <% else %>
    <%= link_to 'Add new account', new_account_path %>
  <% end %> |
  <%= link_to 'Download all', '/accounts.csv' %>
</p>

<div class="filter-area">
  <%= render 'transactions/dates' %>
</div>

<h3>Non-retirement:</h3>

<%= render 'activity_table', accounts: @non_retirement_accounts, nets: @nets %>

<h3>Retirement:</h3>

<%= render 'activity_table', accounts: @retirement_accounts, nets: @nets %>

<h3>External:</h3>

<%= render 'activity_table', accounts: @external_accounts, nets: @nets %>

app/views/accounts/new.html.erb
<h2>Add a new account</h2>

<%= render 'form' %>

<%= link_to 'Cancel', accounts_path %>

app/views/accounts/show.html.erb
<h2>Account info</h2>

<%= render 'flash', key: :error %>

<%= render 'account' %>

<p>
  <%= link_to 'Previous', account_path(@account.previous) %> |
  <%= link_to 'Next', account_path(@account.next) %> |
  <% if Mode.demo? %>
    <%= link_to 'Edit', account_path(@account),
      data: {confirm: "Editing is not available in demo mode"} %> |
    <%= link_to 'Delete', account_path(@account),
      data: { confirm: 'Deleting is not available in demo mode' } %>
  <% else %>
    <%= link_to 'Edit', edit_account_path(@account) %> |
    <%= link_to 'Delete', account_path(@account), data: {
      turbo_method: :delete, turbo_confirm: 'Are you sure?'
    } %>
  <% end %>
</p>

<h3>Transactions involving this account</h3>

<%= render 'transactions/filters' %>

<%= render 'transactions/summary', content: [['Count', @count],
                                             ['Input', @input],
                                             ['Output', @output],
                                             ['Net', @net]] %>

<%= render 'transactions/table', account: @account %>